import { ConvexError, v } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";
import type { Id } from "./_generated/dataModel";
import { mutation, query, type MutationCtx } from "./_generated/server";
import { requireAdmin } from "./admin";

// Per 07 §10: prizeEntries are NEVER inserted from a donation flow.
// This mutation is the only path that adds a row to the table. Donor
// must (a) be authenticated, (b) own the donation, (c) the donation
// must be paid. Idempotent — re-clicking returns the existing entry id.

export interface OptInArgs {
  donationId: Id<"donations">;
  userId: Id<"users">;
}

export interface OptInResult {
  entryId: Id<"prizeEntries">;
  alreadyEntered: boolean;
}

export async function _optInForTest(
  ctx: MutationCtx,
  args: OptInArgs,
): Promise<OptInResult> {
  const donation = await ctx.db.get(args.donationId);
  if (!donation) throw new ConvexError("donation_not_found");
  if (donation.userId !== args.userId) throw new ConvexError("forbidden");
  if (donation.status !== "paid") throw new ConvexError("donation_not_paid");

  const existing = await ctx.db
    .query("prizeEntries")
    .withIndex("by_donation", (q) => q.eq("donationId", args.donationId))
    .first();
  if (existing) {
    return { entryId: existing._id, alreadyEntered: true };
  }

  const entryId = await ctx.db.insert("prizeEntries", {
    donationId: args.donationId,
    userId: args.userId,
    method: "online" as const,
  });
  return { entryId, alreadyEntered: false };
}

export const optIn = mutation({
  args: { donationId: v.id("donations") },
  handler: async (ctx, { donationId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new ConvexError("unauthenticated");
    return await _optInForTest(ctx, { donationId, userId });
  },
});

// Read-only check used by the success page to decide which button copy
// to render: "Enter the prize draw (free)" vs "You're entered".
export const isEntered = query({
  args: { donationId: v.id("donations") },
  handler: async (ctx, { donationId }) => {
    const existing = await ctx.db
      .query("prizeEntries")
      .withIndex("by_donation", (q) => q.eq("donationId", donationId))
      .first();
    return existing !== null;
  },
});

// --- Prize draw -----------------------------------------------------
//
// Audit algorithm (published in the prize T&Cs):
//   1. Snapshot all prizeEntries at the moment of the draw.
//   2. Sort the entry ids ascending.
//   3. Take the first 8 hex chars of the seed and parse as uint32.
//   4. winnerIndex = (uint32 % entryCount).
//
// Anyone given the seed + sorted entry ids can replay this and verify
// the winner. The seed is generated by Web Crypto's CSPRNG at the
// moment of the draw and persisted on the prizeDraws row.

export function pickWinnerIndex(seedHex: string, count: number): number {
  if (count <= 0) {
    throw new Error("count must be positive");
  }
  const slice = seedHex.slice(0, 8);
  if (!/^[0-9a-fA-F]{8}$/.test(slice)) {
    throw new Error("seed must start with at least 8 hex chars");
  }
  const value = Number.parseInt(slice, 16);
  return value % count;
}

function generateSeed(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export interface RunDrawArgs {
  drawName: string;
  seed?: string;
  runByUserId: Id<"users">;
}

export interface RunDrawResult {
  drawId: Id<"prizeDraws">;
  alreadyRun: boolean;
  drawName: string;
  seed: string;
  entryCount: number;
  entryIds: Id<"prizeEntries">[];
  winnerEntryId: Id<"prizeEntries">;
  winnerDonationId: Id<"donations">;
}

export async function _runDrawForTest(
  ctx: MutationCtx,
  args: RunDrawArgs,
): Promise<RunDrawResult> {
  const existing = await ctx.db
    .query("prizeDraws")
    .withIndex("by_name", (q) => q.eq("drawName", args.drawName))
    .first();
  if (existing) {
    return {
      drawId: existing._id,
      alreadyRun: true,
      drawName: existing.drawName,
      seed: existing.seed,
      entryCount: existing.entryCount,
      entryIds: existing.entryIds,
      winnerEntryId: existing.winnerEntryId,
      winnerDonationId: existing.winnerDonationId,
    };
  }

  const entries = await ctx.db.query("prizeEntries").collect();
  if (entries.length === 0) {
    throw new ConvexError("no_entries");
  }

  const sorted = entries
    .map((e) => e._id)
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));

  const seed = args.seed ?? generateSeed();
  const winnerIndex = pickWinnerIndex(seed, sorted.length);
  const winnerEntryId = sorted[winnerIndex]!;
  const winnerEntry = entries.find((e) => e._id === winnerEntryId)!;

  const drawId = await ctx.db.insert("prizeDraws", {
    drawName: args.drawName,
    seed,
    entryCount: sorted.length,
    entryIds: sorted,
    winnerEntryId,
    winnerDonationId: winnerEntry.donationId,
    runByUserId: args.runByUserId,
  });

  return {
    drawId,
    alreadyRun: false,
    drawName: args.drawName,
    seed,
    entryCount: sorted.length,
    entryIds: sorted,
    winnerEntryId,
    winnerDonationId: winnerEntry.donationId,
  };
}

export const runDraw = mutation({
  args: {
    drawName: v.string(),
    seed: v.optional(v.string()),
  },
  handler: async (ctx, { drawName, seed }): Promise<RunDrawResult> => {
    const admin = await requireAdmin(ctx);
    return await _runDrawForTest(ctx, {
      drawName,
      seed,
      runByUserId: admin.userId,
    });
  },
});

// Read-only audit lookup. Admin-only — exposes the seed and entry
// snapshot so an admin can copy them into the published audit page.
export const getDraw = query({
  args: { drawName: v.string() },
  handler: async (ctx, { drawName }) => {
    await requireAdmin(ctx);
    const draw = await ctx.db
      .query("prizeDraws")
      .withIndex("by_name", (q) => q.eq("drawName", drawName))
      .first();
    return draw;
  },
});
