import { ConvexError, v } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";
import type { Id } from "./_generated/dataModel";
import { mutation, query, type MutationCtx } from "./_generated/server";
import { logAdminAction, requireAdmin } from "./admin";
import { consumeRateLimit, RATE_LIMITS } from "./rateLimit";

// Per 07 §10: prizeEntries are NEVER inserted from a donation flow.
// This mutation is the only path that adds a row to the table. Donor
// must (a) be authenticated, (b) own the donation, (c) the donation
// must be paid. Idempotent — re-clicking returns the existing entry id.

export interface OptInArgs {
  donationId: Id<"donations">;
  userId: Id<"users">;
}

export interface OptInResult {
  entryId: Id<"prizeEntries">;
  alreadyEntered: boolean;
}

export async function _optInForTest(
  ctx: MutationCtx,
  args: OptInArgs,
): Promise<OptInResult> {
  const donation = await ctx.db.get(args.donationId);
  if (!donation) throw new ConvexError("donation_not_found");
  if (donation.userId !== args.userId) throw new ConvexError("forbidden");
  if (donation.status !== "paid") throw new ConvexError("donation_not_paid");

  await consumeRateLimit(
    ctx,
    `prizeOptIn:${args.donationId}`,
    RATE_LIMITS.prizeOptIn,
  );

  const existing = await ctx.db
    .query("prizeEntries")
    .withIndex("by_donation", (q) => q.eq("donationId", args.donationId))
    .first();
  if (existing) {
    return { entryId: existing._id, alreadyEntered: true };
  }

  const entryId = await ctx.db.insert("prizeEntries", {
    donationId: args.donationId,
    userId: args.userId,
    method: "online" as const,
  });
  return { entryId, alreadyEntered: false };
}

export const optIn = mutation({
  args: { donationId: v.id("donations") },
  handler: async (ctx, { donationId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new ConvexError("unauthenticated");
    return await _optInForTest(ctx, { donationId, userId });
  },
});

// Read-only check used by the success page to decide which button copy
// to render: "Enter the prize draw (free)" vs "You're entered".
export const isEntered = query({
  args: { donationId: v.id("donations") },
  handler: async (ctx, { donationId }) => {
    const existing = await ctx.db
      .query("prizeEntries")
      .withIndex("by_donation", (q) => q.eq("donationId", donationId))
      .first();
    return existing !== null;
  },
});

// --- Prize draw -----------------------------------------------------
//
// Audit algorithm (published in the prize T&Cs):
//   1. Snapshot all prizeEntries at the moment of the draw.
//   2. Sort the entry ids ascending.
//   3. Take the first 8 hex chars of the seed and parse as uint32.
//   4. winnerIndex = (uint32 % entryCount).
//
// Anyone given the seed + sorted entry ids can replay this and verify
// the winner. The seed is generated by Web Crypto's CSPRNG at the
// moment of the draw and persisted on the prizeDraws row.

export function pickWinnerIndex(seedHex: string, count: number): number {
  if (count <= 0) {
    throw new Error("count must be positive");
  }
  const slice = seedHex.slice(0, 8);
  if (!/^[0-9a-fA-F]{8}$/.test(slice)) {
    throw new Error("seed must start with at least 8 hex chars");
  }
  const value = Number.parseInt(slice, 16);
  return value % count;
}

function generateSeed(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export interface RunDrawArgs {
  drawName: string;
  seed?: string;
  runByUserId: Id<"users">;
}

export interface RunDrawResult {
  drawId: Id<"prizeDraws">;
  alreadyRun: boolean;
  drawName: string;
  seed: string;
  entryCount: number;
  entryIds: string[];
  winnerType: "online" | "postal";
  winnerEntryRef: string;
  winnerOnlineEntryId: Id<"prizeEntries"> | null;
  winnerPostalEntryId: Id<"postalEntries"> | null;
  winnerDonationId: Id<"donations"> | null;
}

const ONLINE_PREFIX = "online:";
const POSTAL_PREFIX = "postal:";

export async function _runDrawForTest(
  ctx: MutationCtx,
  args: RunDrawArgs,
): Promise<RunDrawResult> {
  const existing = await ctx.db
    .query("prizeDraws")
    .withIndex("by_name", (q) => q.eq("drawName", args.drawName))
    .first();
  if (existing) {
    return {
      drawId: existing._id,
      alreadyRun: true,
      drawName: existing.drawName,
      seed: existing.seed,
      entryCount: existing.entryCount,
      entryIds: existing.entryIds,
      winnerType: existing.winnerType,
      winnerEntryRef: existing.winnerEntryRef,
      winnerOnlineEntryId: existing.winnerOnlineEntryId ?? null,
      winnerPostalEntryId: existing.winnerPostalEntryId ?? null,
      winnerDonationId: existing.winnerDonationId ?? null,
    };
  }

  const onlineEntries = await ctx.db.query("prizeEntries").collect();
  const postalEntries = await ctx.db.query("postalEntries").collect();
  const total = onlineEntries.length + postalEntries.length;
  if (total === 0) {
    throw new ConvexError("no_entries");
  }

  const refs: string[] = [
    ...onlineEntries.map((e) => `${ONLINE_PREFIX}${e._id}`),
    ...postalEntries.map((e) => `${POSTAL_PREFIX}${e._id}`),
  ];
  refs.sort();

  const seed = args.seed ?? generateSeed();
  const winnerIndex = pickWinnerIndex(seed, refs.length);
  const winnerRef = refs[winnerIndex]!;

  const isPostal = winnerRef.startsWith(POSTAL_PREFIX);
  const winnerType: "online" | "postal" = isPostal ? "postal" : "online";
  const rawId = winnerRef.slice(
    (isPostal ? POSTAL_PREFIX : ONLINE_PREFIX).length,
  );

  let winnerOnlineEntryId: Id<"prizeEntries"> | null = null;
  let winnerPostalEntryId: Id<"postalEntries"> | null = null;
  let winnerDonationId: Id<"donations"> | null = null;
  if (isPostal) {
    winnerPostalEntryId = rawId as Id<"postalEntries">;
  } else {
    winnerOnlineEntryId = rawId as Id<"prizeEntries">;
    const winnerOnline = onlineEntries.find((e) => e._id === rawId);
    winnerDonationId = winnerOnline?.donationId ?? null;
  }

  const drawId = await ctx.db.insert("prizeDraws", {
    drawName: args.drawName,
    seed,
    entryCount: refs.length,
    entryIds: refs,
    winnerType,
    winnerEntryRef: winnerRef,
    winnerOnlineEntryId: winnerOnlineEntryId ?? undefined,
    winnerPostalEntryId: winnerPostalEntryId ?? undefined,
    winnerDonationId: winnerDonationId ?? undefined,
    runByUserId: args.runByUserId,
  });

  return {
    drawId,
    alreadyRun: false,
    drawName: args.drawName,
    seed,
    entryCount: refs.length,
    entryIds: refs,
    winnerType,
    winnerEntryRef: winnerRef,
    winnerOnlineEntryId,
    winnerPostalEntryId,
    winnerDonationId,
  };
}

// Admin-keyed postal entry. UK Gambling Commission requires a free
// postal route for charity prize draws; this is the only ingest path.
export interface AddPostalEntryArgs {
  name: string;
  address: string;
  enteredByUserId: Id<"users">;
}

export async function _addPostalEntryForTest(
  ctx: MutationCtx,
  args: AddPostalEntryArgs,
): Promise<{ postalEntryId: Id<"postalEntries"> }> {
  const name = args.name.trim();
  const address = args.address.trim();
  if (name.length === 0) throw new ConvexError("postal_name_required");
  if (address.length === 0) throw new ConvexError("postal_address_required");
  if (name.length > 200) throw new ConvexError("postal_name_too_long");
  if (address.length > 1000) throw new ConvexError("postal_address_too_long");

  const id = await ctx.db.insert("postalEntries", {
    name,
    address,
    receivedAt: Date.now(),
    enteredByUserId: args.enteredByUserId,
  });
  return { postalEntryId: id };
}

export const adminAddPostalEntry = mutation({
  args: { name: v.string(), address: v.string() },
  handler: async (ctx, { name, address }) => {
    const admin = await requireAdmin(ctx);
    const result = await _addPostalEntryForTest(ctx, {
      name,
      address,
      enteredByUserId: admin.userId,
    });
    await logAdminAction(ctx, admin, {
      action: "postalEntry.add",
      targetType: "postalEntry",
      targetId: result.postalEntryId,
      metadata: { name },
    });
    return result;
  },
});

export const adminListPostalEntries = query({
  args: {},
  handler: async (ctx) => {
    await requireAdmin(ctx);
    const rows = await ctx.db
      .query("postalEntries")
      .withIndex("by_received")
      .order("desc")
      .take(500);
    return rows.map((r) => ({
      postalEntryId: r._id,
      name: r.name,
      address: r.address,
      receivedAt: r.receivedAt,
    }));
  },
});

export const runDraw = mutation({
  args: {
    drawName: v.string(),
    seed: v.optional(v.string()),
  },
  handler: async (ctx, { drawName, seed }): Promise<RunDrawResult> => {
    const admin = await requireAdmin(ctx);
    const result = await _runDrawForTest(ctx, {
      drawName,
      seed,
      runByUserId: admin.userId,
    });
    if (!result.alreadyRun) {
      await logAdminAction(ctx, admin, {
        action: "prizeDraw.run",
        targetType: "draw",
        targetId: result.drawId,
        metadata: {
          drawName: result.drawName,
          entryCount: result.entryCount,
          winnerType: result.winnerType,
          winnerEntryRef: result.winnerEntryRef,
        },
      });
    }
    return result;
  },
});

// Read-only audit lookup. Admin-only — exposes the seed and entry
// snapshot so an admin can copy them into the published audit page.
export const getDraw = query({
  args: { drawName: v.string() },
  handler: async (ctx, { drawName }) => {
    await requireAdmin(ctx);
    const draw = await ctx.db
      .query("prizeDraws")
      .withIndex("by_name", (q) => q.eq("drawName", drawName))
      .first();
    return draw;
  },
});
