import type { Stand } from "./geometry";

// Per-stand prices match the live mock (blue-for-bob-v4.html line 311+):
// premium £50 (South Stand), standard £25 (Hollies/Stanley/West),
// general £10 (Wyatt/Priory). Money is integer pence everywhere.
export const STANDS: readonly Stand[] = [
  {
    id: "hollies",
    name: "Eric Hollies Stand",
    sub: "The Famous Stand",
    tier: "standard",
    vStart: 313,
    vEnd: 47,
    innerR: 133,
    rows: 13,
    pricePence: 2_500,
  },
  {
    id: "wyatt",
    name: "Wyatt Stand",
    sub: "RES Wyatt",
    tier: "general",
    vStart: 47,
    vEnd: 90,
    innerR: 131,
    rows: 7,
    pricePence: 1_000,
  },
  {
    id: "stanley",
    name: "Stanley Barnes",
    sub: "East Side",
    tier: "standard",
    vStart: 90,
    vEnd: 148,
    innerR: 131,
    rows: 8,
    pricePence: 2_500,
  },
  {
    id: "south",
    name: "South Stand",
    sub: "Pavilion End",
    tier: "premium",
    vStart: 148,
    vEnd: 212,
    innerR: 133,
    rows: 10,
    pricePence: 5_000,
  },
  {
    id: "west",
    name: "West Stand",
    sub: "",
    tier: "standard",
    vStart: 212,
    vEnd: 298,
    innerR: 133,
    rows: 11,
    pricePence: 2_500,
  },
  {
    id: "priory",
    name: "Priory Stand",
    sub: "Family Stand",
    tier: "general",
    vStart: 298,
    vEnd: 313,
    innerR: 130,
    rows: 5,
    pricePence: 1_000,
  },
];
